### ISSUE TITLE
Dependency on `f` seems incorrect

### ISSUE THREAD

**Issue by mdorman** [mrkkrp/ebal#3]
So, there's actually two issues.  One is that `ebal` depends on `f` version 1.6...which doesn't actually exists.  The latest release of `f` is 0.17.2.  But that ultimately doesn't matter because you depend on a function `f-swap-ext` that doesn't exist in that version, and there hasn't been a release tagged since that was introduced.

So I was hoping you could add your support to rejeep/f.el#48 asking, as a consumer of the library, that a new release be tagged so it can be picked up on melpa-stable, and you can depend on it properly.

**Comment by mrkkrp** [comment]
Hi, @mdorman, thanks for the heads up. I don't remember now why I put `1.6` as version of `f` :-D I will see what I can do if the author if `f` explicitly asks for help of certain kind. Another option is to replace invocation of `f-swap-ext` with equivalent code so we can depend on released versions of `f`.

You've probably opened the issue because you're experiencing issues with `ebal` installation. Are you using MELPA stable and you cannot install `ebal` because of its “bad” dependency list? In this case I'll undertake immediate actions so you can use `ebal` without long delay.

**Comment by mdorman** [comment]
Hi, @mrkkrp, I appreciate your quick response.  Also, I really appreciate `ebal`. :smile:

At this point, I have a working configuration for myself, and I would be more interested in seeing if we could get a new release of `f` that you could then properly depend on.

As background: a couple of days ago, I thought it would be interesting to see if I could work with 'melpa-stable', rather than tracking the bleeding edge of 'melpa'---in large part because `melpa-stable` serves as a more reasonable base for distributions (like nixos, which I use) to package emacs packages---and so I undertook to downgrade as many of my packages as I could, and have subsequently been observing the effects, and trying to report appropriate bugs.

I did momentarily experience issues with `ebal`, but I have worked around it (by installing the `melpa` version of `f`), so I'm not blocked or anything, and in my personal view---which should certainly not govern your opinion or response, though I would like you to consider it---it is more useful to try and build awareness among maintainers of emacs packages about this sort of issue, to see that the right thing is done over the long term---and you don't have to needlessly duplicate code that only lacks a release that you can depend on.

**Comment by mrkkrp** [comment]
@mdorman, `f 0.18.0` has been released, I've fixed that dependency and tagged `ebal 0.1.2`, it will be available via MELPA stable soon. I think this issue can be closed now.
